apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-pvc
  namespace: {{ .Values.config.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-rwx